import { Color } from "littlejsengine";
import { OPERATION_TYPE } from "./types";

export const MAX_NUMBER = 99;

export enum DIFFICULTY {
    easy = "easy", medium = "medium", hard = "hard"
};

export enum GAME_STATE {
    PLAYING, LOSE, WIN
}

export const OPERATION_SEQUENCES = {
    easy: [
        [OPERATION_TYPE.ADD, OPERATION_TYPE.MUL],
        [OPERATION_TYPE.MUL, OPERATION_TYPE.ADD],
        [OPERATION_TYPE.ADD, OPERATION_TYPE.DIV],
        [OPERATION_TYPE.SUB, OPERATION_TYPE.MUL],
        [OPERATION_TYPE.MUL, OPERATION_TYPE.SUB],
        [OPERATION_TYPE.SUB, OPERATION_TYPE.DIV],
    ],
    medium: [
        [OPERATION_TYPE.ADD, OPERATION_TYPE.MUL, OPERATION_TYPE.SUB],
        [OPERATION_TYPE.ADD, OPERATION_TYPE.DIV, OPERATION_TYPE.SUB],
        [OPERATION_TYPE.MUL, OPERATION_TYPE.ADD, OPERATION_TYPE.DIV],
        [OPERATION_TYPE.MUL, OPERATION_TYPE.SUB, OPERATION_TYPE.DIV],
        [OPERATION_TYPE.SUB, OPERATION_TYPE.MUL, OPERATION_TYPE.ADD],
        [OPERATION_TYPE.SUB, OPERATION_TYPE.DIV, OPERATION_TYPE.ADD],

    ],
    hard: [
        [OPERATION_TYPE.ADD, OPERATION_TYPE.MUL, OPERATION_TYPE.SUB, OPERATION_TYPE.DIV],
        [OPERATION_TYPE.ADD, OPERATION_TYPE.DIV, OPERATION_TYPE.SUB, OPERATION_TYPE.MUL],
        [OPERATION_TYPE.MUL, OPERATION_TYPE.ADD, OPERATION_TYPE.DIV, OPERATION_TYPE.SUB],
        [OPERATION_TYPE.MUL, OPERATION_TYPE.SUB, OPERATION_TYPE.DIV, OPERATION_TYPE.ADD], 
        [OPERATION_TYPE.SUB, OPERATION_TYPE.MUL, OPERATION_TYPE.ADD, OPERATION_TYPE.DIV],
        [OPERATION_TYPE.SUB, OPERATION_TYPE.DIV, OPERATION_TYPE.ADD, OPERATION_TYPE.MUL],
    ]
};

export const COLOR_PALETTE = {
    RED: new Color(231/255, 111/255, 81/255, 1), // #E76F51
    ORANGE: new Color(244/255, 162/255, 97/255, 1), // #F4A261
    YELLOW: new Color(233/255, 196/255, 106/255, 1), // #E9C46A
    GREEN: new Color(42/255, 157/255, 143/255, 1), // #2A9D8F
    BLUE: new Color(38/255, 70/255, 83/255, 1), // #264653
    WHITE: new Color(238/255, 238/255, 238/255, 1), // #EEEEEE
    TRANSPARENT: new Color(0, 0, 0, 0)
};